from pipeline import processs_top_view_data

data_path = '/net/dk-server/afassihizakeri/movies_Rat_SC_project/ar2muscimol500nl500igmar13muscimolleft5ul500nl/10_11_19'
processs_top_view_data(data_path)